### ISSUE TITLE
反馈AndroidDimens问题

### ISSUE THREAD

**Issue by tcqq** [chenglei1986/AndroidDimens#3]
你好，我将参考设计稿尺寸设置为1080x1920，然后我在垂直滚动布局添加了2个按钮，按钮高度都设为1920px，但是最后显示出来的效果没有将状态栏高度算进去，但是不是所有手机状态栏的高度都相同，这种情况应该怎么做呢？
![qq 20170930110255](https://user-images.githubusercontent.com/10644057/31041903-66f342aa-a5cf-11e7-8513-a8bbfb16b6f3.png)
![screenshot_20170930-110200](https://user-images.githubusercontent.com/10644057/31041904-6725034e-a5cf-11e7-91a6-b4522da1ec89.png)

**Comment by chenglei1986** [comment]
@TCQQ Android手机屏幕尺寸比较多，有的还有虚拟按键什么的，所以我的适配思路是从屏幕宽度上（最窄那一边）入手，比如设计稿上有个正方形的控件，宽度是屏幕的三分之一，我可以保证在所有手机上都是占屏幕三分之一。
Android本身也提供了一些屏幕适配的属性，比如最基本的"match_parent"，还有LinearLayout的"layout_weight"属性等，像你这种情况最好用"match_parent"属性来做。

**Comment by tcqq** [comment]
但是这是滚动布局，match_parent无法实现这种效果

**Comment by chenglei1986** [comment]
你说的是水平滚动，在高度上应该是可以的啊

**Comment by tcqq** [comment]
sorry，是垂直滚动

**Comment by tcqq** [comment]
刚刚测了下，横屏后高度不会自动转换

**Comment by chenglei1986** [comment]
横屏肯定不会自动转换，因为你写的px1920，那就是1080P屏幕上的1920个像素。你要是用垂直方向的ViewPager肯定是能用match_parent的，但是ScrollView就没办法了，代码算吧。

**Comment by tcqq** [comment]
http://blog.csdn.net/zhengjingle/article/details/51742839

**Comment by tcqq** [comment]
这个库可以解决目前存在的所有问题https://github.com/zhengjingle/Autolayout分享给你
这个库目前只发现一个小问题，你可以看看https://github.com/zhengjingle/Autolayout/issues/2
如果有好的解决方案可以告诉我，谢谢

**Comment by chenglei1986** [comment]
他这个是按比例来算的，出现的问题就是，如果屏幕比例和设计稿不一样，就会出现issue里的情况。
比如设计稿是16:9，那么对华为这种因为虚拟导航栏实际屏幕比例只有16:10以及最近出现的18:9全面屏来说都是不能用的

**Comment by tcqq** [comment]
是的

**Comment by tcqq** [comment]
这个问题应该怎么做才能解决呢

**Comment by chenglei1986** [comment]
让UI去学下设计规范，不符合规范的设计不要做，我这个其实算是官方适配教程的一个变体，官方的意思是，比如你有个分割线宽度名字叫divider_height，在sw320dp文件夹下写成
<dimen name="divider_height">0.4dp</dimen>
在sw480dp文件夹下写成
<dimen name="divider_height">0.6dp</dimen>

我这里不过把所有设计稿的不同像素写成了px1、px2 ... 等等

**Comment by chenglei1986** [comment]
或者你说服产品和设计，这里的交互改成ViewPager的交互方式

**Comment by tcqq** [comment]
找到了个好东西https://github.com/amphiaraus/Android-RatioLayout

**Comment by chenglei1986** [comment]
这个很简单，改一下每个控件的onMesure方法就行了，但是还是不能解决你的问题

**Comment by TCQQ** [comment]
这个是按比例布局

**Comment by TCQQ** [comment]
但是那个库目前暂时不支持横屏时调换比例，如果能实现横屏时调换比例，布局将能够完全适配
